package com.luckhouse.housekeeper.db.entity;

// Generated 2014-8-10 16:26:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Tallytype generated by hbm2java
 */
@Entity
@Table(name = "tallytype", catalog = "housekeeper")
public class Tallytype implements java.io.Serializable {

	private static final long serialVersionUID = -8855400616151986411L;
	private Integer id;
	private String type;
	private Tally tally;

	public Tallytype() {
	}

	public Tallytype(String type, Tally tally) {
		this.type = type;
		this.tally = tally;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tallytype")
	public Tally getTally() {
		return this.tally;
	}

	public void setTally(Tally tally) {
		this.tally = tally;
	}

}
