package com.luckhouse.housekeeper.db.entity;

// Generated 2014-8-10 16:26:15 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "housekeeper")
public class User implements java.io.Serializable {
	
	private static final long serialVersionUID = -1485359029409258461L;
	private Integer id;
	private String email;
	private String displayName;
	private String password;
	private String username;

	public User() {
	}

	public User(String password, String username) {
		this.password = password;
		this.username = username;
	}
	public User(Integer id, String email, String displayName, String password,
			String username) {
		super();
		this.id = id;
		this.email = email;
		this.displayName = displayName;
		this.password = password;
		this.username = username;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "displayName")
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}
